/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encrypter */

#ifndef _Included_Encrypter
#define _Included_Encrypter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encrypter
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Encrypter_encrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
